# Generated by Django 4.1.5 on 2023-01-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brikoblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
