# Generated by Django 4.1.5 on 2023-01-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brikoblog', '0009_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
